### ISSUE TITLE
DataBase selection

### ISSUE THREAD

**Issue by ksreyr** [Juan-Avila92/SPL-Indicator#2]

**Comment by ksreyr** [comment]
Do you want to use a specific DB? or can i pick a random one?

**Comment by Juan-Avila92** [comment]
I would like to learn about SQL. What do you think about it?

**Comment by ksreyr** [comment]
@Juan-Avila92  
it would be possible but we need to create a consistent Model, I mean Classes and Tables etc. 
About that reason a think that something like MongoDB or Firebase maybe could be the better solution for this problem. 
you could read about it in this link:
[SQL (MySQL) vs NoSQL (CouchDB) ](https://stackoverflow.com/questions/2559411/sql-mysql-vs-nosql-couchdb)

**Comment by ksreyr** [comment]
BD_ selected is Postgress
